# Generated by Django 5.0.4 on 2024-04-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('des', models.TextField()),
                ('image', models.FileField(default=None, max_length=200, null=True, upload_to='myapp/')),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
